---
# Self-hosted Git service
- name: Installing Gitea on OrangePi
  block:
    - name: Gitea Git clone
      ansible.builtin.git:
        repo: 'https://github.com/hufhend/gitea.git'
        dest: /home/{{ docker_user }}/{{ docker_home }}/gitea
        force: true

    # - name: Enable Gitea on port 22
    #   ansible.builtin.lineinfile:
    #     path: /home/{{ docker_user }}/{{ docker_home }}/gitea/docker-compose.yaml
    #     regexp: '^ *- "222:22"'
    #     line: '      - "22:22"'

    - name: Create and start Gitea
      community.docker.docker_compose_v2:
        project_src: /home/{{ docker_user }}/{{ docker_home }}/gitea
      # register: output
  when: inventory_hostname == 'git.akira.cz'
