---
- name: Check if swap file exists
  ansible.builtin.stat:
    path: "{{ swap_path }}/{{ swap_file }}"
  register: swap_file_check

- name: Install swap file
  block:
    - name: Create swap file
      ansible.builtin.command: touch "{{ swap_path }}/{{ swap_file }}"

    - name: Allocate swap file
      ansible.builtin.command: fallocate -l {{ swap_size }} "{{ swap_path }}/{{ swap_file }}"

    # - name: Create swap space
    #   command: dd if=/dev/zero of=/swapfile bs=1024 count=3670016

    - name: Set permissions on swap file
      ansible.builtin.file:
        path: "{{ swap_path }}/{{ swap_file }}"
        mode: 0600

    - name: Format swap file
      ansible.builtin.command: mkswap "{{ swap_path }}/{{ swap_file }}"

    - name: Add swap to fstab
      ansible.builtin.lineinfile:
        dest: /etc/fstab
        regexp: "{{ swap_path }}/{{ swap_file }}"
        line: "{{ swap_path }}/{{ swap_file }} none swap sw 0 0"

    - name: Turn on swap
      ansible.builtin.command: swapon -a

    - name: Set swapiness
      ansible.posix.sysctl:
        name: vm.swappiness
        value: "1"
      
  when: not swap_file_check.stat.exists

- name: Shorten history for sysstat
  ansible.builtin.lineinfile:
    path: /etc/sysstat/sysstat
    regexp: '^HISTORY=7'
    line: 'HISTORY=3'

- name: Keep history for sysstat
  ansible.builtin.lineinfile:
    path: /etc/sysstat/sysstat
    regexp: '^COMPRESSAFTER=10'
    line: 'COMPRESSAFTER=1'

- name: Install Git packages
  ansible.builtin.apt:
    pkg:
      - git

- name: Create a docker directory
  ansible.builtin.file:
    path: /home/{{ docker_user }}/docker
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: '0750'

- name: Check if Prometheus exists
  ansible.builtin.stat:
    path: /home/{{ docker_user }}/docker/prometheus
  register: prometheus_dir_check

- name: Install Prometheus in Docker
  block:
    - name: Prometheus Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/hufhend/prometheus.git'
        dest: /home/{{ docker_user }}/docker/prometheus
        # single_branch: yes
        # version: master

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /home/{{ docker_user }}/docker/prometheus
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: '0744'
        recurse: yes
        
    - name: Create a directory structure
      ansible.builtin.command: sh init.sh
      # become: yes
      become_user: "{{ docker_user }}"
      args:
        chdir: /home/{{ docker_user }}/docker/prometheus/

    - name: Create and start services
      community.docker.docker_compose:
        project_src: /home/{{ docker_user }}/docker/prometheus/
      become_user: "{{ docker_user }}"
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output

  when:  not prometheus_dir_check.stat.exists