---
- name: Gather facts for first time
  ansible.builtin.setup:

- name: Ping all hosts
  ansible.builtin.ping:
  register: ping_result

- name: Set hostname by inventory
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Add Ansible user
  ansible.builtin.user:
    name: "{{ user_ansible }}"
    create_home: true
    skeleton: /etc/skel
    shell: /bin/bash
    uid: 2000
    state: present
  when: ansible_user != user_ansible

- name: Check if the sudoers file exists
  ansible.builtin.stat:
    path: "/etc/sudoers.d/{{ user_ansible }}"
  register: sudoers_file

- name: Upload the sudoers template
  template:
    src: templates/sudoers.j2
    dest: "/etc/sudoers.d/{{ user_ansible }}"
    owner: root
    group: root
    mode: '0640'
  when: not sudoers_file.stat.exists

# - name: Show pub_key_file
#   debug:
#     var: pub_key_file

- name: Add Ansible authorized ssh key
  ansible.posix.authorized_key:
    key: "{{ lookup('file', item.key) }}"
    user: "{{ user_ansible }}"
    state: "{{ item.state | default(omit) }}"
  when: item.key is exists
  loop: "{{ pub_key_file }}"

