---
# tasks file for cluster_node
- name: Status check and update
  ansible.builtin.apt:
    state: fixed
    update_cache: true
- name: System upgrade
  ansible.builtin.apt:
    name: "*"
    state: latest
  #  upgrade: dist
    autoremove: true
- name: Set timezone to Europe/Prague
  ansible.builtin.timezone:
    name: Europe/Prague
- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - htop
    - screen
    - mc
    - sysstat
    - smartmontools
    - lm-sensors
    - fail2ban
    - open-iscsi
    - nfs-common
    - ethtool
- name: Enable sysstat in /etc/default/sysstat
  ansible.builtin.lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED='
    line: 'ENABLED="true"'
    backup: true
- name: Start the sysstat service
  ansible.builtin.systemd:
    name: sysstat
    state: started
    enabled: true