---
# block sleeping - especially for NTB
- name: Modify HandleLidSwitch setting
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^#?HandleLidSwitch='
    line: 'HandleLidSwitch=ignore'

- name: Modify IdleAction setting
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^#?IdleAction='
    line: 'IdleAction=ignore'

- name: Check if UPower exists
  ansible.builtin.stat:
    path: /etc/UPower/UPower.conf
  register: upower_conf

- name: Modify IgnoreLid setting
  ansible.builtin.lineinfile:
    path: /etc/UPower/UPower.conf
    regexp: '^IgnoreLid='
    line: 'IgnoreLid=true'
  when: upower_conf.stat.exists

# block the start of GNOME Virtual File System
- name: Check if ubuntu-desktop is installed
  command: apt list -a ubuntu-desktop
  register: ubuntu_desktop_status
  ignore_errors: true

- name: Disable desktop service
  block:
  - name: Disable service gvfs-afc
    ansible.builtin.systemd_service:
      name: gvfs-afc-volume-monitor
      enabled: false
      masked: yes
  - name: Disable service gvfs-daemon
    ansible.builtin.systemd_service:
      name: gvfs-daemon
      enabled: false
      masked: yes
  - name: Disable service gvfs-goa
    ansible.builtin.systemd_service:
      name: gvfs-goa-volume-monitor
      enabled: false
      masked: yes
  - name: Disable service gvfs-gphoto2
    ansible.builtin.systemd_service:
      name: gvfs-gphoto2-volume-monitor
      enabled: false
      masked: yes
  - name: Disable service gvfs-metadata
    ansible.builtin.systemd_service:
      name: gvfs-metadata
      enabled: false
      masked: yes
  - name: Disable service gvfs-mtp
    ansible.builtin.systemd_service:
      name: gvfs-mtp-volume-monitor
      enabled: false
      masked: yes
  - name: Disable service udisks2
    ansible.builtin.systemd_service:
      name: gvfs-udisks2-volume-monitor
      enabled: false
      masked: yes
  - name: Disable service gdm
    ansible.builtin.systemd_service:
      name: gdm
      enabled: false
  - name: Disable service snap
    ansible.builtin.systemd_service:
      name: snapd
      enabled: false
  when: "'ubuntu-desktop' in ubuntu_desktop_status.stdout or 'instal' in ubuntu_desktop_status.stdout"

- name: Add Wake-On-Lan service
  ansible.builtin.template:
    src: templates/wol-enable.service.j2
    dest: "/etc/systemd/system/wol-enable.service"
    owner: root
    group: root
    mode: '0644'

- name: Wake-on-LAN activation at startup
  ansible.builtin.systemd_service:
    name: wol-enable
    enabled: true

- name: Install keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present

- name: Add keepalived service
  ansible.builtin.template:
    src: templates/keepalived_worker.j2
    dest: "/etc/keepalived/keepalived.conf"
    owner: root
    group: root
    mode: '0644'
  when: role == 'worker'

- name: Add keepalived service
  ansible.builtin.template:
    src: templates/keepalived_master.j2
    dest: "/etc/keepalived/keepalived.conf"
    owner: root
    group: root
    mode: '0644'
  when: role == 'master'

- name: Add keepalived service
  ansible.builtin.template:
    src: templates/keepalived_combi.j2
    dest: "/etc/keepalived/keepalived.conf"
    owner: root
    group: root
    mode: '0644'
  when: role == 'combi'
