---
# block sleeping - especially for NTB
- name: Modify HandleLidSwitch setting
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^#?HandleLidSwitch='
    line: 'HandleLidSwitch=ignore'

- name: Modify IdleAction setting
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^#?IdleAction='
    line: 'IdleAction=ignore'

- name: Check if UPower exists
  ansible.builtin.stat:
    path: /etc/UPower/UPower.conf
  register: upower_conf

- name: Modify IgnoreLid setting
  ansible.builtin.lineinfile:
    path: /etc/UPower/UPower.conf
    regexp: '^IgnoreLid='
    line: 'IgnoreLid=true'
  when: upower_conf.stat.exists

# block the start of GNOME Virtual File System
- name: Check if ubuntu-desktop is installed
  command: apt list -a ubuntu-desktop
  register: ubuntu_desktop_status
  ignore_errors: true

- name: Include tasks disable desktop services
  include_tasks: "{{ role_path }}/tasks/desktop_services.yaml"
  when: "'ubuntu-desktop' in ubuntu_desktop_status.stdout or 'instal' in ubuntu_desktop_status.stdout"

# set and enable Wake-on-LAN
- name: Add Wake-on-LAN service
  ansible.builtin.template:
    src: templates/wol-enable.service.j2
    dest: "/etc/systemd/system/wol-enable.service"
    owner: root
    group: root
    mode: '0644'

- name: Wake-on-LAN activation at startup
  ansible.builtin.systemd_service:
    name: wol-enable
    enabled: true

# high availability via keepalived
- name: Install keepalived service
  ansible.builtin.apt:
    name: keepalived
    state: present

- name: Add keepalived worker
  ansible.builtin.template:
    src: templates/keepalived_worker.j2
    dest: "/etc/keepalived/keepalived.conf"
    owner: root
    group: root
    mode: '0644'
  when: role == 'worker'

- name: Add keepalived master
  ansible.builtin.template:
    src: templates/keepalived_master.j2
    dest: "/etc/keepalived/keepalived.conf"
    owner: root
    group: root
    mode: '0644'
  when: role == 'master'

- name: Add keepalived combi
  ansible.builtin.template:
    src: templates/keepalived_combi.j2
    dest: "/etc/keepalived/keepalived.conf"
    owner: root
    group: root
    mode: '0644'
  when: role == 'combi'
