---
- name: Set timezone to Europe/Prague
  ansible.builtin.timezone:
    name: Europe/Prague
- name: Ensure a Czech locale exists
  community.general.locale_gen:
    name: cs_CZ.UTF-8
    state: present
- name: Set as default locale
  ansible.builtin.shell: localectl set-locale LANG=cs_CZ.UTF-8 LANGUAGE=CZ.UTF-8 LC_MESSAGES=cs_CZ.UTF-8 LC_TIME=cs_CZ.UTF-8 && locale-gen
  when: ansible_env['LANG'] != 'cs_CZ.UTF-8'

