---
- name: Set timezone to Europe/Prague
  ansible.builtin.timezone:
    name: Europe/Prague

- name: Ensure a Czech locale exists
  community.general.locale_gen:
    name: cs_CZ.UTF-8
    state: present
  when: ansible_os_family | lower != "redhat"

# # Make your selection and comment here
# - name: Set Czech as the default locale
#   ansible.builtin.shell: localectl set-locale LANG=cs_CZ.UTF-8 LC_MESSAGES=cs_CZ.UTF-8 LC_TIME=cs_CZ.UTF-8
#   when: ansible_env['LANG'] != 'cs_CZ.UTF-8'

- name: Set English as the default locale
  ansible.builtin.shell: localectl set-locale LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_TIME=en_US.UTF-8
  when: ansible_env['LANG'] != 'en_US.UTF-8'
