---
- name: Create a docker directory
  ansible.builtin.file:
    path: /home/{{ docker_user }}/docker
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_user }}"
    mode: '0750'

# Automated ACME SSL certificate generation for nginx-proxy
- name: Clone acme-companion in Docker
  block:
    - name: ACME companion Git clone
      ansible.builtin.git:
        repo: 'https://github.com/hufhend/acme-companion.git'
        dest: /home/{{ docker_user }}/docker/acme-companion

- name: Create and start ACME services
  community.docker.docker_compose_v2:
    project_src: /home/{{ docker_user }}/docker/acme-companion
  # register: output

# Monitoring Prometheus with Grafana
- name: Check if Prometheus exists
  ansible.builtin.stat:
    path: /home/{{ docker_user }}/docker/prometheus
  register: prometheus_dir_check

- name: Clone Prometheus in Docker
  block:
    - name: Prometheus Git clone
      ansible.builtin.git:
        repo: 'https://github.com/hufhend/prometheus.git'
        dest: /home/{{ docker_user }}/docker/prometheus
        # single_branch: yes
        # version: master

    - name: Change file permissions
      ansible.builtin.file:
        path: /home/{{ docker_user }}/docker/prometheus
        owner: "{{ docker_user }}"
        group: "{{ docker_user }}"
        mode: '0744'
        recurse: yes
        
    - name: Create a directory structure
      ansible.builtin.command: sh init.sh
      args:
        chdir: /home/{{ docker_user }}/docker/prometheus

    - name: Create and start Prometheus
      community.docker.docker_compose_v2:
        project_src: /home/{{ docker_user }}/docker/prometheus
      register: output

    # - name: Create and start services
    #   ansible.builtin.command: docker compose up -d
    #   args:
    #     chdir: /home/{{ docker_user }}/docker/prometheus
    #   register: output

    - name: Show results
      ansible.builtin.debug:
        var: output
  when:  not prometheus_dir_check.stat.exists

# Self-hosted Git service
- name: Clone Gitea in Docker
  block:
    - name: Gitea Git clone
      ansible.builtin.git:
        repo: 'https://github.com/hufhend/gitea.git'
        dest: /home/{{ docker_user }}/docker/gitea

- name: Create and start Gitea
  community.docker.docker_compose_v2:
    project_src: /home/{{ docker_user }}/docker/gitea
  # register: output