---
- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
    state: present

# - name: Add Docker Repository
#   ansible.builtin.deb822_repository:
#     name: docker
#     uris: https://download.docker.com/linux/ubuntu

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker
  apt:
    pkg:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin
    state: latest
    update_cache: true

# - name: Install Docker Module for Python
#   pip:
#     name: docker

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
