---
- name: Setting up and updating the operating system
  hosts: all
  become: true
  roles:
    - role: system_upgrade
    - role: env_settings
    - role: orangepi
    - role: docker
    - role: firewall
  vars:
    swap_file: swapfile
    swap_path: "" # empty for root
    swap_size: 3.5G
    ansible_user: hufhendr