- name: My first play
  hosts: myhosts
  become: yes
  become_method: sudo
  vars:
    ansible_user: hufhendr
  tasks:
  #  - name: Ping my hosts
  #    ansible.builtin.ping:
  #  - name: Print message
  #    ansible.builtin.debug:
  #     msg: Hello world

   - name: Status check and update
     apt:
       state: fixed
       update_cache: yes
   - name: System upgrade
     apt:
       name: "*"
       state: latest
      #  upgrade: dist
       autoremove: true
   - name: Install a list of packages
     apt:
       pkg:
       - apt-transport-https 
       - ca-certificates 
       - curl
       - htop 
       - screen 
       - mc 
       - sysstat 
       - smartmontools 
       - lm-sensors 
       - fail2ban 
       - open-iscsi 
       - nfs-common 
       - ethtool
   - name: Enable sysstat in /etc/default/sysstat
     lineinfile:
       path: /etc/default/sysstat
       regexp: '^ENABLED='
       line: 'ENABLED="true"'
       backup: yes
   - name: Start the sysstat service
     systemd:
       name: sysstat
       state: started
       enabled: yes
   - name: Set timezone to Europe/Prague
     timezone:
       name: Europe/Prague

