- name: My first play
  hosts: myhosts
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
      msg: Hello world

   - name: Status check and update
     become: yes
     apt:
       state: fixed
       update_cache: yes
   - name: System upgrade
     become: yes
     ansible.builtin.apt:
       name: "*"
       state: latest
      #  upgrade: dist
       autoremove: true
   - name: Install a list of packages
     become: yes
     apt:
       pkg:
       - apt-transport-https 
       - ca-certificates 
       - curl
       - htop 
       - screen 
       - mc 
       - sysstat 
       - smartmontools 
       - lm-sensors 
       - fail2ban 
       - open-iscsi 
       - nfs-common 
       - ethtool
   - name: Enable sysstat in /etc/default/sysstat
     become: yes
     lineinfile:
       path: /etc/default/sysstat
       regexp: '^ENABLED='
       line: 'ENABLED=true'
       backup: yes
   - name: Start the sysstat service
     become: yes
     systemd:
       name: sysstat
       state: started
       enabled: yes

